# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AL3SA8RF3wW5s-TDbQR1eFXiO4JGw-ID

**DATA CLEANING**
"""

# Imports Libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv("Nagpur_Crimes.csv")

# Overview
print("Shape: ",df.shape)
df.head()

# Structure of Dataset
df.info()

# Missing values
print("\nMissing values:\n", df.isnull().sum())

# Handling Missing Crime_Type (603 missing)
print("Crime_Type missing percentage", (df['Crime_Type'].isnull().sum() / len(df)) * 100)

# Dropping the rows where crime_type is missing
df = df.dropna(subset=['Crime_Type'])
print("\nMissing Values:\n",df.isnull().sum())

#Handling Missing values for Time and Date
print("Time missing %:", (df['Time'].isnull().sum() / len(df)) * 100)
print("Date missing %:", (df['Date'].isnull().sum() / len(df)) * 100)

# Drop rows where either Time or Date is missing
df = df.dropna(subset=['Time', 'Date'])
print("\nMissing values:\n", df.isnull().sum())

#Convert dates to proper datetime format
df['Time'] = pd.to_datetime(df['Time'], format='%H:%M', errors='coerce')

#Convert to datetime formats again (cleanly)
df['Time'] = pd.to_datetime(df['Time'], errors='coerce')
df['Hour'] = df['Time'].dt.hour

df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
df['Month'] = df['Date'].dt.to_period('M')

df

#Remove Duplicates
print("Shape before removing duplicates:", df.shape)
df = df.drop_duplicates()
print("Shape after removing duplicates:", df.shape)
print("\nColumn data types:\n", df.dtypes)

#check if there are still missing values present or not
df.isnull().sum()

#Downloading the cleaned dataset
df.to_csv('Nagpur_Crimes_CLEANED.csv', index=False)

#checking how many rows left after cleaning
df

"""**DATA ANALYSIS**"""

#Crime Count by Hour of the Day
df['Hour'].value_counts().sort_index()

#Top 3 Most Common Crime Types
df['Crime_Type'].value_counts().head(3)

# Areas with Highest Crime Reports
df['Area'].value_counts().head(10)

#Most Common Crime Types in Each Zone
df.groupby('Zone')['Crime_Type'].value_counts().groupby(level=0).head(1)

#Count of Each Case Status (Solved/Pending)
df['Status'].value_counts()

#Monthly Crime Trends
df.groupby('Month').size().sort_index()

"""**DATA VISUALIZATION**"""

import matplotlib.pyplot as plt
import seaborn as sns

# Top 10 crime-prone areas
top_areas = df['Area'].value_counts().head(10)

plt.figure(figsize=(10,6))
sns.barplot(x=top_areas.values, y=top_areas.index, palette='Reds_r')
plt.title("Top 10 Crime-Prone Areas in Nagpur")
plt.xlabel("Number of Crimes")
plt.ylabel("Area")
plt.tight_layout()
plt.show()

#Is crime increasing over time?
monthly_trend = df.groupby('Month').size()

plt.figure(figsize=(12,5))
monthly_trend.plot(marker='o', color='royalblue')
plt.title("Crime Trend Over Time (Monthly)")
plt.xlabel("Month")
plt.ylabel("Number of Crimes")
plt.grid(True)
plt.tight_layout()
plt.show()
